// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyM8PpE9cmxczxwrJAvGvgSRrbp6txCU',
    appId: '1:660068081564:web:4cdae81210dbfc0827f259',
    messagingSenderId: '660068081564',
    projectId: 'todo-app-d5704',
    authDomain: 'todo-app-d5704.firebaseapp.com',
    storageBucket: 'todo-app-d5704.appspot.com',
    measurementId: 'G-0SJP9FSQR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxqFa0pzPuwelU3hcpRGJeaOW38Z1sBk',
    appId: '1:660068081564:android:06a6c566ea36bb0027f259',
    messagingSenderId: '660068081564',
    projectId: 'todo-app-d5704',
    storageBucket: 'todo-app-d5704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHY-41Sn-TvceGSZK6IDrzAzcVIlukgo',
    appId: '1:660068081564:ios:a252b542bb82804227f259',
    messagingSenderId: '660068081564',
    projectId: 'todo-app-d5704',
    storageBucket: 'todo-app-d5704.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHY-41Sn-TvceGSZK6IDrzAzcVIlukgo',
    appId: '1:660068081564:ios:a252b542bb82804227f259',
    messagingSenderId: '660068081564',
    projectId: 'todo-app-d5704',
    storageBucket: 'todo-app-d5704.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoyM8PpE9cmxczxwrJAvGvgSRrbp6txCU',
    appId: '1:660068081564:web:85a105ac2ff5124e27f259',
    messagingSenderId: '660068081564',
    projectId: 'todo-app-d5704',
    authDomain: 'todo-app-d5704.firebaseapp.com',
    storageBucket: 'todo-app-d5704.appspot.com',
    measurementId: 'G-JWEM44DC3Z',
  );
}
